# Generated by Django 3.1.12 on 2024-12-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20241213_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='quizuser',
            table='quiz_quizuser',
        ),
    ]
